# =============================================================================
# ATLAS System Configuration v4.0
# =============================================================================
# Головний конфігураційний файл для системи ATLAS
# =============================================================================

# Загальні налаштування системи
atlas:
  version: "4.0"
  name: "ATLAS - Adaptive Task and Learning Assistant System"
  debug: false
  log_level: "INFO"

# Порти сервісів
ports:
  goose_server: 3000        # Goose Web Server (AI Engine)
  frontend: 5001            # Python Frontend (Web Interface)  
  orchestrator: 5101        # Node.js Orchestrator (Agent Management)
  recovery_bridge: 5102     # Recovery Bridge (System Recovery)
  tts_service: 3001         # Ukrainian TTS Service
  fallback_llm: 3010        # Fallback LLM (за потреби)

# Конфігурація Goose
goose:
  desktop_path: "/Applications/Goose.app/Contents/MacOS/goose"
  use_desktop: true
  server_port: 3000
  websocket_timeout: 120    # секунд
  retry_attempts: 3
  retry_delay: 1000         # мілісекунди
  token_limit: 2000         # символів для текстів в промптах

# Агенти системи
agents:
  atlas:
    name: "ATLAS"
    role: "coordinator"
    color: "#00ff00"
    signature: "[ATLAS]"
    voice: "dmytro"
    priority: 1
    description: "Координатор, стратег, куратор завдань"
  
  tetyana:
    name: "ТЕТЯНА"
    role: "executor"
    color: "#00ffff"
    signature: "[ТЕТЯНА]"
    voice: "tetiana"
    priority: 2
    description: "Основний виконавець завдань"
  
  grisha:
    name: "ГРИША"
    role: "verificator"
    color: "#ffff00"
    signature: "[ГРИША]"
    voice: "mykyta"
    priority: 3
    description: "Верифікатор, контроль якості"

# TTS (Text-to-Speech) налаштування
tts:
  enabled: true
  server_url: "http://127.0.0.1:3001"
  device: "mps"             # mps для Apple Silicon, cpu для Intel
  real_mode: true           # true для реального TTS, false для mock
  default_voice: "dmytro"
  supported_voices:
    - "dmytro"
    - "tetiana"
    - "mykyta"
    - "oleksa"

# Workflow конфігурація
workflow:
  max_stages: 9
  max_retries: 3
  timeout_per_stage: 300    # секунд
  enable_verification: true
  auto_recovery: true

# Логування
logging:
  enabled: true
  directory: "./logs"
  archive_directory: "./logs/archive"
  max_file_size: "10MB"
  rotation_count: 5
  files:
    orchestrator: "orchestrator.log"
    frontend: "frontend.log"
    goose: "goose_web.log"
    tts: "tts.log"
    recovery: "recovery_bridge.log"

# Налаштування безпеки
security:
  enable_cors: true
  allowed_origins: ["*"]
  api_timeout: 30           # секунд
  max_request_size: "10MB"

# Fallback система
fallback:
  enabled: false            # Локальний fallback LLM
  port: 3010
  model: "llama2"

# Моніторинг та діагностика
monitoring:
  health_check_interval: 30 # секунд
  performance_metrics: true
  error_tracking: true
  auto_diagnostics: true

# Середовище виконання
environment:
  force_free_ports: true
  auto_recovery: true
  clean_logs_on_start: false
  development_mode: false
