# =============================================================================
# ATLAS System Configuration v4.0 - Modular Architecture Edition
# =============================================================================
# Системний конфігураційний файл для ATLAS
# 
# ВАЖЛИВО: Конфігурації агентів, TTS, workflow та API endpoints
# перенесено в shared-config.js для уніфікації всіх компонентів
# =============================================================================

# Загальні налаштування системи
atlas:
  version: "4.0"
  name: "ATLAS - Adaptive Task and Learning Assistant System"
  debug: false
  log_level: "INFO"

# Порти сервісів
ports:
  goose_server: 3000        # Goose Web Server (AI Engine)
  frontend: 5002            # Python Frontend (Web Interface) - оновлений порт  
  orchestrator: 5101        # Node.js Orchestrator (Agent Management)
  recovery_bridge: 5102     # Recovery Bridge (System Recovery)
  tts_service: 3001         # Ukrainian TTS Service
  fallback_llm: 4000        # Fallback LLM (за потреби)

# Конфігурація Goose
goose:
  desktop_path: "/opt/homebrew/bin/goose"
  use_desktop: true
  server_port: 3000
  websocket_timeout: 120    # секунд
  retry_attempts: 3
  retry_delay: 1000         # мілісекунди
  token_limit: 2000         # символів для текстів в промптах

# ПРИМІТКА: Конфігурації агентів, TTS та workflow перенесено в shared-config.js
# Це забезпечує єдину конфігурацію для всіх компонентів системи
# Детальні налаштування дивіться в файлі shared-config.js

# Системні налаштування TTS (тільки технічні параметри)
tts:
  device: "mps"             # mps для Apple Silicon, cpu для Intel
  real_mode: true           # true для реального TTS, false для mock
  server_url: "http://127.0.0.1:3001"

# Системні налаштування workflow (тільки технічні параметри)
workflow:
  timeout_per_stage: 300    # секунд
  auto_recovery: true

# Логування
logging:
  enabled: true
  directory: "./logs"
  archive_directory: "./logs/archive"
  max_file_size: "10MB"
  rotation_count: 5
  files:
    orchestrator: "orchestrator.log"
    frontend: "frontend.log"
    goose: "goose_web.log"
    tts: "tts.log"
    recovery: "recovery_bridge.log"

# Налаштування безпеки
security:
  enable_cors: true
  allowed_origins: ["*"]
  api_timeout: 30
  max_request_size: "10MB"

# Fallback система
fallback:
  enabled: false
  port: 4000
  model: "mistral-ai/ministral-3b"

# Моніторинг та діагностика
monitoring:
  health_check_interval: 30
  performance_metrics: true
  error_tracking: true
  auto_diagnostics: true

# Середовище виконання
environment:
  force_free_ports: true
  auto_recovery: true
  clean_logs_on_start: false
  development_mode: false
